language: node_js
sudo: required
node_js:
- 6
- 7
- node
before_install:
- npm install -g npm@5
- npm install -g greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
script:
- npm run build
- npm run test
env:
  global:
    secure: Iy4utvTiOMFOFQ81tB8GVm1pTimZGOS1/p1tLvQNM1imb95BEmK5pwQCjxXZxGYmNUNhresvZnURpGmARueAIVHP6Iwu1a2L9K5d0YfpQYDgLbFvyjHRNQP4y7S6pmmtVCdOyPzgN37s3yUy0bxlTmWLHcy8WMSGp4S3fxSGNUnYmn8/sEusAK92RjCYAm1fdIVxSAisxkQaUC4MD+qOytfNXXWmVtpiJQ31toAjNCfMjYFq4nHDFVQ1ML6WVsD7qRiRCxnWBWrUCaf5puwQfTI8PrktQ888mgY/foiI/1Oe2tbS2Px6D88WSfBCdI7ynwEFdsRlQwIARQuRPbyFKploub1DjcFcBb6sL1DXo/uBoXMnQoXoe29Gy3TFZ8wMfnw0MZkGU/nGPO6OciqybBfasMsAA/oGrmjMjFNcJ9xLyPTWrB7d5PQhiKPWSxvUjScQPmtLcpuM+rB3bFeilT8qEDFFTAJMxeQ0WxwvS7auxTChX5QjCV/shw9sv60/qGm/DwLzeminMNL4w2NvXo9CDF1hCnoOiOl/6VfQDLWZclDkH2kTHPAWu0b/b+xje7pVTjNTFIOQhMN79tVcJNkRfl9PWLEZ4IrMjTlUhDz+ADW7eN8pJq60lXXRtZ7JP1/iijZUGdsswXENML4G0X1lbq+sDok0LdMosp7BvI4=
deploy:
  on:
    tags: true
    branch: master
    skip_cleanup: true
  api_key:
    secure: efqDqFyHDsKb1Gp0hxMwlhrWHglFsNFnC4hwYkDs4lLmdw3M+HbBCqYytnfEceZtA4fPG/g4zTsCCb1UgioSAO6OH4uU0EcrPBUMc9vInmDWwMXikZoqkvMkOt/7ewspt5ttmwE3QNhbQlaFfSlM684GQWWEv+ZT4709z0oBlMyE7zQ+SQGbiC9LU4wSxbgFGB5+DahuwisVXAb7xhtPvNBjihcONUtVrG4sOMxczLXjf2rgwU4Vo373OKK80vKUUrcCTBeTgUsEwFGFkUhL61k/Giu0qj2Wf9u+/FZZwCkBumLAjisQjBHboxcQY/4YuUS/wcpPC39WCZ9XwfEZIo9EosD2EU+zBmVJDLTBrKkyuft4ufhoYQnT+mGspf5RIR8/V0ywHoYgtkCkgZ+83nYz8lcL+HEI1Ohp+Ex6wQKl0YDdg+SqHIw27ZSWlsZbttc2IEGGMmMA/1E/TnCgIY3v9zHC7x/ypc7F105SiN2cFYhMVd9iQhZjmNUcvdR1GVDIcztts6C1hUxASsHgoIGDP71TxDVwyXXKAtOyibms8k0KCB0jPfcNNoOatNTIZSczNroA2rqgMTry7Q3aH52ryCK0y7BSgYtceXXaNbzAU28kT2J93XqF85bnTgy14EwyoXg0q7TjmDUBha2DhGvvxri44ifgfxij0ymjF38=
